.gitignore
app/services/import_service.rb
spec/services/assignment_service_spec.rb
spec/services/import_service_spec.rb

Amended log output for import sort on date for answer

Amended tests that were intermittently failing on papertrail

---

app/assets/stylesheets/pq.scss
app/controllers/action_officer_reminder_controller.rb
app/views/dashboard/_question_data.html.slim
app/views/dashboard/_question_data_commissioned.html.slim
app/views/pq_mailer/acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.text.erb
app/views/pq_mailer/acceptance_reminder_email.html.erb
app/views/pq_mailer/acceptance_reminder_email.text.erb
app/views/pq_mailer/commission_email.html.erb
app/views/pq_mailer/commission_email.text.erb
app/views/pq_mailer/notify_dd_email.html.erb
app/views/pq_mailer/notify_dd_email.text.erb
app/views/pq_mailer/watchlist_email.html.erb
app/views/pq_mailer/watchlist_email.text.erb
app/views/shared/_navigation.html.slim
app/views/shared/mailer/_email_signature.html.slim
app/views/shared/mailer/_email_signature_plain.text.slim
app/views/watchlist_dashboard/index.html.slim

This update includes the following:
PT84108818 - UIN now links to the details pages and the 'PQ Details' link has been removed.
PT84112594 - The Minister email links have been removed.

Feedback links added to web pages and application generated emails.

---

app/assets/stylesheets/minister-select.scss

I have refactored the  scss, added comments, prettified code.

Refactored minister-select.scss

---

app/assets/javascripts/ministerSelect.js
app/assets/javascripts/pq.js
app/assets/javascripts/trim_link.js

Added comments and Refactored java script files

Added comments and Refactored java script files 

---

app/assets/javascripts/pq.js
app/assets/javascripts/trim_link.js

, Referenced the trim_linkobject in the PQ.js file and added a trim_link object and applied this to each trim function

added a trim_link object and applied this to each trim function

---

app/views/assignment/index.html.slim

See https://trello.com/c/aHAo6coi/14-accept-reject-page-no-response-flag-bug

place no-response case back in main if

---

Gemfile
Gemfile.lock
README.md
app/controllers/pqs_controller.rb
app/controllers/watchlist_members_controller.rb
app/controllers/watchlist_send_emails_controller.rb
app/services/token_service.rb
app/services/watchlist_report_service.rb
app/views/assignment/index.html.slim
app/views/shared/_question_assigned.html.slim
app/views/watchlist_dashboard/index.html.slim
features/finance_officer_spec.rb
features/watch_list_spec.rb
spec/feature_helper.rb
spec/services/token_service_spec.rb
spec/services/watchlist_report_service_spec.rb
spec/spec_helper.rb
spec/support/db_helpers.rb
spec/support/features/session_helpers.rb

- Completed test coverage for "watcher sees allocated questions card"
- Minor changes of form data item 
- Reworked feature helper to handle suspending database cleaner

Watch list test

---

app/assets/javascripts/pq.js
app/controllers/commission_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/pqs_controller.rb
app/models/commission_form.rb
app/services/commissioning_service.rb
app/views/assignment/index.html.slim
app/views/dashboard/_question_data_uncommissioned.html.slim
app/views/pq_mailer/commission_email.text.erb
app/views/shared/_minister_selection.html.slim
app/views/shared/_question_assigned.html.slim
app/views/watchlist_dashboard/index.html.slim
features/commission_question_spec.rb
features/dashboard_spec.rb
features/finance_officer_spec.rb
features/watch_list_spec.rb
spec/feature_helper.rb
spec/services/assignment_service_spec.rb
spec/services/commissioning_service_spec.rb
spec/spec_helper.rb
spec/support/db_helpers.rb
spec/support/features/email_helpers.rb

Add tests for question commission timeout
Extracted common test functionality to email helper module
Tweaked RSpec db clean setup
Refactored watch_list_spec

Pq commission timeout

---

app/controllers/action_officer_reminder_controller.rb
features/ao_reminder_email_spec.rb
features/commision_question_spec.rb

Implements scenario [Trello card ](https://trello.com/c/h3Z6lrqQ/42-tc-pb-sends-reminder-email-to-ao).
Also refactors controller logic

Parli-branch sends reminder email to Action Officers

---

app/assets/stylesheets/pq.scss
app/views/dashboard/_question_data_commissioned.html.slim
app/views/dashboard/_question_data_uncommissioned.html.slim

- on dashboard, make what's editable grey
- on pq progress, make every label grey

make labels more consistent

---

app/views/action_officers/index.html.slim
app/views/actionlist_members/index.html.slim
app/views/directorates/index.html.slim
app/views/divisions/index.html.slim
app/views/press_desks/index.html.slim
app/views/watchlist_members/index.html.slim

six files have been up dated to remove the tbody being added to the tr element.

fixed elements error in table rows

---

app/models/pq.rb
features/transferring_questions_spec.rb
spec/models/pq_spec.rb

+ Added test coverage for transferred in questions workflow
+ Corrected uin whitespace stripping

Added TC for transferring PQ workflow

---

app/assets/javascripts/pq.js
app/assets/stylesheets/pq.scss
app/views/answering/_form.html.slim
app/views/assignment/show.html.slim
app/views/shared/_commissioned.html.slim
app/views/shared/_errors.html.slim
config/environments/development.rb

On finding more classes named "alert" in scss and and js, we updated these classes to the new pq-msg-error or success.

Fix alerts

---

app/assets/javascripts/pq.js
app/views/layouts/application.html.slim
config/application.rb

To be reviewed by Mel and then Andrea before merging to dev

Google analytics

---

lib/export/base.rb

+ Corrected error in CSV export class

fixed typo

---

app/assets/stylesheets/pq.scss

added form-lable class to progress-panel to fix text style in the checkbox.

checkbox text syling

---

app/assets/stylesheets/pq.scss
app/controllers/export_controller.rb
app/controllers/minister_contacts_controller.rb
app/services/commissioning_service.rb
app/views/minister_contacts/edit.html.slim
app/views/minister_contacts/show.html.slim
app/views/ministers/show.html.slim

- Fix a regression whereby we commissioning fails on empty Deputy directors' emails
- Fix CSV export date ranges
- Revert button styling
- Allow editing/disabling minister contacs

Hotfix release: 1.19.16

---

README.md
app/controllers/action_officer_reminder_controller.rb
app/mailers/pq_mailer.rb
app/models/press_desk.rb
app/services/commissioning_service.rb
app/views/layouts/application.html.slim
app/views/pq_mailer/acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.text.erb
app/views/pq_mailer/acceptance_reminder_email.html.erb
app/views/pq_mailer/acceptance_reminder_email.text.erb
app/views/pq_mailer/commission_email.html.erb
app/views/pq_mailer/commission_email.text.erb
app/views/pq_mailer/draft_reminder_email.html.erb
app/views/pq_mailer/draft_reminder_email.text.erb
app/views/pq_mailer/notify_dd_email.html.erb
app/views/pq_mailer/notify_dd_email.text.erb
app/views/pq_mailer/watchlist_email.html.erb
app/views/pq_mailer/watchlist_email.text.erb
app/views/shared/mailer/_email_signature_plain.text.slim
features/commision_question_spec.rb
spec/mailers/action_officer_reminder_mailer_spec.rb
spec/models/press_desk_spec.rb

Revised all the template emails HTML and TEXT versions to reflect new wording

Email copy changes

---

app/views/action_officers/_form.html.slim
app/views/actionlist_members/_form.html.slim
app/views/deputy_directors/_form.html.slim
app/views/minister_contacts/_form.html.slim
app/views/ministers/_form.html.slim
app/views/press_officers/_form.html.slim
app/views/users/edit.html.slim
app/views/watchlist_members/_form.html.slim

check to make sure that all fields actually need email addresses (or else could be empty)

client-side validate all email fields

---

features/commision_question_spec.rb
features/post_commissioning_spec.rb
spec/support/features/pq_helpers.rb

Also add helper method `expect_pq_in_progress_status`

Add scenario for PQ post-commissioning workflow

---

.travis.yml
features/finance_officer_spec.rb
features/import_spec.rb
spec/support/features/email_helpers.rb

+ Added test coverage for finance user invitation
- Removed unnecessary Import test

Added test coverage for finance user invitation

---

app/controllers/action_officers_controller.rb
app/models/action_officer.rb
app/views/action_officers/edit.html.slim
app/views/action_officers/new.html.slim
features/action_officer_spec.rb

+ Added test coverage for action officer creation
+ Refactored action officer controller
+ Added validation of uniqueness of AO email for deputy director (this is also enforced at database level)
+ Removed poor error handling of previous implementation

Ao controller refactor

---

app/controllers/commission_controller.rb
app/controllers/export_controller.rb
app/controllers/pqs_controller.rb
app/controllers/transferred_controller.rb
app/models/action_officer.rb
app/models/actionlist_member.rb
app/models/watchlist_member.rb
app/services/whitespace_validator.rb
app/views/transferred/new.html.slim
features/csv_export_spec.rb
features/rejecting_aos.rb
features/transfer_in_pq_spec.rb
features/transfer_out_pq_spec.rb
lib/validators/date_input.rb
lib/validators/whitespace.rb
spec/lib/validators/date_input_spec.rb

+ Created date input validator
+ Moved whitespace validation into validator module
+ Added date validation to all controllers
+ Added flash error to create transferred PQ
+ Added test coverage for date validation

Security date sanitize

---

app/controllers/i_will_write_controller.rb
app/models/pq.rb
app/views/pqs/_answer.html.slim
db/migrate/20150306114738_follow_up_to.rb
db/schema.rb
features/mark_a_question_as_iww_spec.rb
features/post_commissioning_spec.rb

Implement end-to-end test and push logic into the PQ model

Refactor IWW behaviour

---

app/controllers/commission_controller.rb
app/controllers/pqs_controller.rb
spec/lib/validators/date_input_spec.rb

+ Bug fix: now restrict outrageous times

bug fix - outrageous times now restricted

---

app/controllers/manual_reject_commission_controller.rb
app/controllers/search_controller.rb
app/controllers/trim_links_controller.rb
app/models/trim_link.rb
features/dashboard_spec.rb
lib/validators/trim.rb

+ Added test coverage for dashboard functionality
+ Refactor manually commission controller
+ Refactor search controller
+ Move trim validation into Validators module

Refactor manual reject and search controllers

---

app/controllers/manual_reject_commission_controller.rb
app/controllers/minister_contacts_controller.rb
app/helpers/application_helper.rb
app/views/pq_mailer/.#acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.text.erb
app/views/pq_mailer/acceptance_reminder_email.html.erb
app/views/pq_mailer/acceptance_reminder_email.text.erb
app/views/pq_mailer/commission_email.html.erb
app/views/pq_mailer/commission_email.text.erb
app/views/pq_mailer/draft_reminder_email.html.erb
app/views/pq_mailer/draft_reminder_email.text.erb
app/views/pq_mailer/notify_dd_email.html.erb
app/views/pq_mailer/notify_dd_email.text.erb
app/views/pq_mailer/watchlist_email.html.erb
app/views/pq_mailer/watchlist_email.text.erb
app/views/shared/mailer/_email_signature.html.slim
app/views/shared/mailer/_email_signature_plain.text.slim

Refactored email content and moved sentences (for any technical issues.....) and  (This is a new service) into the partial footer because it was generic code.

Email checks

---

app/controllers/action_officers_controller.rb
app/controllers/application_controller.rb
app/controllers/assignment_controller.rb
app/controllers/commission_controller.rb
app/controllers/pqs_controller.rb
app/views/layouts/application.html.slim
config/environments/development.rb
config/routes.rb
features/pqs_spec.rb

- return http status code 404 when a record can't be found
- ensure specialized logstash records are written including 'error_page' tag, status, url and referrer for all errors
- change title of error pages for GA

Resource not found

---

app/controllers/application_controller.rb
app/controllers/dashboard_controller.rb

Fix bug where 500 server errors were causing the 404 page to be displayed.

Bug S6-19:404/500 error

---

app/controllers/ogds_controller.rb
app/views/admin/index.html.slim
app/views/assignment/show.html.slim
app/views/ogds/edit.html.slim
app/views/ogds/index.html.slim
app/views/ogds/new.html.slim
app/views/ogds/show.html.slim
db/import/PQ_ETL_ISO.sql

Changes in the SQL file may break something

fix capitalisation and rejection reasons

---

app/models/pq_scopes.rb
spec/models/pq_spec.rb

+ Update PQ sorting SQL query based on user specification
+ Update sorting test for clarity

Updated sorting logic and test to match user feedback

---

app/assets/javascripts/pq.js

- IE7 doesn't like globals
- IE7 stops on some init code, so don't run it unless needed
(the diff shows a lot of change, but a lot of it is indentation)

IE7 choked on assignment page

---

Gemfile
Gemfile.lock
app/controllers/dashboard_controller.rb
app/models/pq_scopes.rb
config/environments/development.rb
spec/controllers/dashboard_controller_spec.rb

- Ensure that sorted_for_dashboard is called when retrieving the dataset, and not on an collection that has already been retrieved.
- write controller specs to test that the collection is in the right order

S6 137 sorted for dashboard

---

config/README.md
lib/rake_task_helpers.rb
lib/rake_task_helpers/db_sanitizer.rb
lib/rake_task_helpers/test_user_config.yml
lib/rake_task_helpers/test_user_generator.rb
lib/tasks/staging_sync.rake
spec/lib/rake_task_helpers/db_sanitizer_spec.rb
spec/lib/rake_task_helpers/sample_config.yml
spec/lib/rake_task_helpers/test_user_generator_spec.rb
spec/spec_helper.rb
spec/support/db_helpers.rb

+ Added rake task to create test users based on .yml file
+ Added rake task to sanitize production data for use in staging

Sync staging

---

LICENSE
config/environments/production.rb

+ Enabled secure cookie flag in prod

S7 126 enabled secure cookies in production only

---

app/mailers/db_sync_mailer.rb
app/mailers/import_mailer.rb
app/mailers/pq_base_mailer.rb
app/views/db_sync_mailer/notify_fail.text.erb
config/initializers/host_env.rb
config/schedule.rb
lib/rake_task_helpers/test_user_config.yml
lib/tasks/staging_sync.rake

+ Added rake task to sanitize prod data for use in staging
+ Added check to ensure task only runs in staging
+ Added cron job to run rake task nightly at 0100 (after db restore)
+ Added Ahana as new test user

S7 106 staging db sync

---

app/assets/stylesheets/pq.scss
app/views/layouts/application.html.slim

added red block message for all pages on staging so users know its not live

added red block message for all pages on staging

---

app/controllers/application_controller.rb
config/environments/production.rb
config/settings.yml
lib/settings.rb
spec/controllers/ssl_config_spec.rb
spec/models/settings_spec.rb

+ Exclude ping.json from force_ssl
+ Allow for additional exclusions in settings.yml

HOTFix - exclude ping.json from forced ssl

---

Gemfile
Gemfile.lock
app/controllers/statistics_controller.rb
app/views/statistics/report.html.slim
config/initializers/business_time.rb
config/initializers/business_time_helpers.rb
config/routes.rb
features/mi_statistics_spec.rb
lib/pq_statistics.rb
lib/pq_statistics/ao_churn.rb
lib/pq_statistics/ao_response_time.rb
lib/pq_statistics/percent_on_time.rb
lib/pq_statistics/time_to_assign.rb
lib/presenters/statistics.rb
lib/tasks/demo.rake
spec/helpers/business_time_helper_spec.rb
spec/lib/pq_statistics/ao_churn_spec.rb
spec/lib/pq_statistics/ao_response_time_spec.rb
spec/lib/pq_statistics/percent_on_time_spec.rb
spec/lib/pq_statistics/time_to_assign_spec.rb
spec/spec_helper.rb

+ Added reporting of % PQs answered on time in weekly buckets
+ Added reporting of AO response time in weekly buckets
+ Added reporting of number of times AO reallocated in weekly buckets
+ Added reporting of time taken to assign AO in weekly buckets

S7-121: Added MI reporting

---

app/controllers/statistics_controller.rb
app/views/statistics/index.html.slim
config/routes.rb

Added index page for statistics routes

---

app/controllers/users/sessions_controller.rb
app/models/user.rb
config/initializers/devise.rb
config/routes.rb
db/migrate/20150427162220_make_devise_users_lockable.rb
db/schema.rb
lib/tasks/user.rake

+ Made user accounts lockable after > 20 failed login attempts
+ Do not leak usernames via forgotten password link
+ Timeout inactive user sessions after 60mins
+ Ensure the rake user:create task can only be run in dev

make authentication more robust

---

app/views/users/edit.html.slim
app/views/users/index.html.slim

and changed the status checkbox on edit page to inactive

Added status on the index page 

---

app/controllers/users/sessions_controller.rb

+ Persist CSRF token when resetting session on user creation
+ Fixes bug on failed login

fix 500 error on failed login

---

app/assets/stylesheets/pq.scss
app/views/layouts/application.html.slim
config/application.rb

Paired and reviewed with Nick in TP

removed Beta Banner and updated the app view and pq.scss

---

.travis.yml
config/settings.yml
lib/rake_task_helpers/staging_sync.rb
lib/rake_task_helpers/test_user_config.yml
lib/tasks/email.rake
lib/tasks/staging_sync.rake
spec/lib/rake_task_helpers/staging_sync_spec.rb
spec/models/settings_spec.rb
spec/spec_helper.rb
spec/workers/import_worker_spec.rb
spec/workers/mail_worker_spec.rb

+ Added test coverage for import worker email functionality
+ Added test coverage for staging db sync functionality
+ Added PQ support as test user to staging

Added test coverage for import and db sync mails

---

app/controllers/statistics_controller.rb
config/routes.rb
features/mi_statistics_spec.rb
lib/pq_statistics/stages_time.rb
lib/pq_statistics/stages_time/journey.rb
lib/pq_statistics/stages_time/stage.rb
lib/presenters/statistics.rb
spec/lib/pq_statistics/stages_time_spec.rb

+ Added calculation for time take for each stage of PQ process: drafting answer, POD clearance, minister clearance, submit answer
+ Added route to return 5 days vs 30 day calculation in JSON
+ Added test coverage for all above

S8 121 mi reporting

---

app/controllers/metrics_dashboard_controller.rb
app/views/metrics_dashboard/index.html.slim
config/schedule.rb
config/settings.yml
lib/gecko_collection.rb
lib/gecko_status.rb
lib/metrics_dashboard.rb
lib/settings.rb
lib/smoke_test_runner.rb
lib/tasks/smoke_test.rake
spec/lib/gecko_collection_spec.rb
spec/lib/smoke_test_runner_spec.rb
spec/models/settings_spec.rb

+ Added rake task to run smoke tests every 1 hour
+ Added smoke test status display to metrics dashboard

Added smoke test regular run + metrics dashboard display

---

app/assets/javascripts/pq.js
app/views/pq_mailer/acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.text.erb
app/views/pq_mailer/commission_email.html.erb
app/views/pq_mailer/commission_email.text.erb
app/views/shared/mailer/_email_signature.html.slim
app/views/shared/mailer/_email_signature_plain.text.slim
config/environments/development.rb
features/commision_question_spec.rb

Internal Deadline for questions has now changed to default to 11am.

Internal deadline eleven

---

app/views/pq_mailer/acceptance_email.html.erb
app/views/pq_mailer/acceptance_email.text.erb

Amended text of emails

---

spec/lib/pq_statistics/stages_time_spec.rb

+ Removed time dependency from stages_time tests

Removed test time dependency

---

app/views/dashboard/_question_data.html.slim

Added underline to UIN

---

app/views/shared/_minister_selection.html.slim
features/commision_question_spec.rb

See https://www.pivotaltracker.com/story/show/96437582

add class to make field mandatory for commissioning

---

app/models/pq.rb
app/models/pq_scopes.rb
lib/gecko_report.rb
spec/lib/gecko_report_spec.rb

Gecko report

---

.travis.yml
app/models/pq_scopes.rb

Date order important for 'between' in activerecord.

Gecko report date

---

app/models/pq_scopes.rb
lib/gecko_report.rb

Exclude Transferred out, count from May

---

app/assets/javascripts/pq.js
app/views/dashboard/_quick_action_edit_dates.html.slim
app/views/pqs/_com_data.html.slim

Change Batch Date update, to batch DateTime updates
+ hide inactive Press Officers on Details:Commission Tab

Quick action edit datetimes

---

lib/rake_task_helpers/db_sanitizer.rb
spec/lib/rake_task_helpers/db_sanitizer_spec.rb

Brakeman Spuriously reporting SQL Injection problem.

Remove brakeman error

---

lib/tasks/bugfix.rake

Question 25231-IWW was created in error. This deletes is, and resets original to be a non-IWW

Remove IWW followup, amend IWW flag of original question

---

lib/presenters/email.rb
spec/mailers/pq_mailers_spec.rb

Add true deadline time

---

.dockerignore
config/database.yml
config/environments/production.rb
docker-compose.env
docker-compose.yml
docker-ng/rails/Dockerfile
docker-ng/rails/logstash-forwarder.sh
docker-ng/rails/make.sh
docker-ng/rails/run-pq.sh
docker-ng/rails/runit/unicorn.service.run-as-user.sample
docker-ng/rails/runit/unicorn.service.sample
lib/pqa/mock_api_server_runner.rb

Lays the initial docker configuration that brings up unicorn.
Let's bring this into upgrade-ruby .. and let's bring in the upgrade-to-ruby-2.3.1 branch into upgrade-ruby as well and try building both.
Opening PR to make sure it passes travis tests.

Redockerise using ruby:2.3.1 container

---

app/mailers/pq_mailer.rb

so we should perform the check of whether we're on staging in a
different way.

We aren't necessarily using an ASSET_HOST

---

app/views/layouts/application.html.slim

moment.js has been included in application.js
while moment.js is not uploaded to S3 bucket

Removed moment.js script tag to clear 499 message

---

lib/tasks/early_bird.rake

Based on this info
https://intranet.justice.gov.uk/news/corp-conference-recess-boxes-and-duty-ministers/

Amend Dates that Earlybird is disallowed

---

docker-ng/rails/Dockerfile
docker-ng/rails/entrypoint.sh

Create docker entrypoint and add APP_HOME/bin to PATH

Create entrypoint and add APP_HOME/bin to PATH

---

lib/tasks/early_bird.rake

Should Re-start on the 19th of June

Amend Dates that the EarlyBird is run

---

lib/tasks/early_bird.rake

Because parliament's new session is delayed

Amend earlybird restart date

---

lib/tasks/early_bird.rake

Conference season 2017

---

lib/tasks/early_bird.rake

Only change restart date, as change happening mid-recess

Amend earlybird for recess

---

.travis.yml
lib/tasks/early_bird.rake

Parliament to reconvene on September 3rd.

Suppress EarlyBird for Summer 2019 Recess

---

lib/tasks/bugfix.rake

Update rake task in order to prefixed last Parlimentary session questions with a '^'.

UPdate session prefix

---

lib/tasks/early_bird.rake

Recess from the 13th to 23rd February 2020.

Suppress the early bird email during recess.

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

https://mojdt.slack.com/archives/C57UPMZLY/p1574844095309800

Fix email protocol

---

lib/tasks/early_bird.rake

-The daily early bird email should not be sent between
29th July & August 31st

CT-2969 Summer 2020 recess early bird suppression

---

.rubocop.yml
app/controllers/dashboard_controller.rb
app/controllers/users/invitations_controller.rb
app/models/commission_form.rb
app/models/trim_link.rb
app/services/quick_actions_service.rb
app/services/token_service.rb
config.ru
lib/pqa/answer_response.rb
lib/smoke_test/dashboard.rb
lib/smoke_test/report.rb
lib/smoke_test/statistics.rb
lib/tasks/import.rake

Fix offenses flagged since upgrading to version 0.88.0

CT-2997 Fix rubocop offenses.

---

app/views/layouts/application.html.slim

Remove banner after RDS upgrade
https://dsdmoj.atlassian.net/browse/CT-3410

CT-3410 Remove banner for RDS

---

app/controllers/application_controller.rb
config/environments/production.rb
config/environments/staging.rb
config/settings.yml
lib/settings.rb
spec/models/settings_spec.rb

Remove controller level force_ssl call in production environment.
Remove force_ssl exclusion on ping.json.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3613
This branch has been deployed to Dev & Staging environments.
Please check the 'Happy' path to check there are no obvious problems:
Try assigning questions to an action officer.
Action officer to accept or reject a question.
Have the pods restarted? etc.

CT-3613 Remove controller level force_ssl call

---

k8s-deploy/staging/deployment.yaml

Currently the Staging environment is only running on 1 pod.  To be a better reflection of the Production environment the deployment will create 4 pods.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3648
This branch has been deployed to both Dev and Staging environments.
'Happy path' checking should not be hidered by pod resets.  Also `$ kubectl get pods` should show 4 running pods.

CT-3648 Update Staging to deploy 4 pods

---

Dockerfile

Security fixe are already done as the base image is correct. Just tidying up the Dockerfile to be consistent with other apps.
Can view on dev. / staging: https://development.trackparliamentaryquestions.service.gov.uk/
https://dsdmoj.atlassian.net/browse/CT-3543
test all deployment
Requries full regression test

CT-3543 Tidy up Dockerfile

---

.circleci/config.yml
config/pipeline/aws_ecr_scan_results.py

Automate security scanning for PQ as per other products
https://dsdmoj.atlassian.net/browse/CT-3542
n/a
Regression test only

CT-3542 Automation script and config for circle

---

.circleci/config.yml
build.sh
deploy.sh
k8s-deploy/production/cronjob-delete-old-ecr-images.yaml
oldbuild.sh

Update refs from master to main
[CT-3626](https://dsdmoj.atlassian.net/browse/CT-3626)

CT-3626 Update refs from master to main

---

app/controllers/early_bird_organiser_controller.rb
app/models/early_bird_organiser.rb
app/views/admin/index.html.slim
app/views/early_bird_organiser/_form.html.slim
app/views/early_bird_organiser/new.html.slim
config/routes.rb
db/migrate/20210623134243_create_early_bird_organisers.rb
db/schema.rb
features/early_bird_organiser_spec.rb
lib/tasks/early_bird.rake
spec/factories/early_bird_organisers.rb
spec/models/early_bird_organiser_spec.rb

Adds ability for users to set times to deactivate the early bird email notifications. 
**Before:**
**After:**
settings page:
New Organise page:
Success message:
Notice on Organise page when 'off' period has been set:
[CT-3313](https://dsdmoj.atlassian.net/browse/CT-3313)
- sign is as an admin
- on the settings page click 'Organise early bird emails'
- Fill in the dates > click submit 
- You should see a success message when you're returned from to the settings page.
- If you click back on the 'Organise early bird emails' you should see an info notice saying that the early bird is turned of between the dates submitted.
- In Dev set a date and then wait for the early bird to not run on that date before moving it on to other envs etc.

Ct 3313 early bird email toggle for users

---

app/views/assignment/show.html.slim

This PR is to change the wording for accepting or rejecting an assignment 
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&modal=detail&selectedIssue=CT-3720

CT-3720 wording change for accept-reject-page

---

app/controllers/early_bird_organiser_controller.rb
app/views/early_bird_organiser/_form.html.slim
app/views/early_bird_organiser/new.html.slim
features/early_bird_organiser_spec.rb

Update copy as per updated ticket.
[CT-3133](https://dsdmoj.atlassian.net/browse/CT-3313)
Submit dates and check associated copy on page.

CT-3133 - Update copy to match updated ticket

---

app/views/early_bird_organiser/_form.html.slim

another very slight wording change.
[CT-3313](https://dsdmoj.atlassian.net/browse/CT-3313)

CT-3313 update copy

---

.github/woeflows/combine-prs.yml
README.md

as on CTS adds action to help merge Dependabot PRs
See [CTS PR](https://github.com/ministryofjustice/correspondence_tool_staff/pull/1714) for more details

Add combine-prs workflow to help with dependabot merges

---

app/views/devise/sessions/new.html.slim

Remove fieldset tag from signin page as there is no legend and it's not needed there.
n/a
https://dsdmoj.atlassian.net/browse/CT-3797
n/a
View source on the sign in page - there should be no 'fieldset' found - but should still work normally.

CT-3797 Remove fieldset tag from signin

---

app/assets/stylesheets/pq.scss
app/views/dashboard/_dashboard_filter.html.slim

Add H1 titles to main three pages
Before: 
After:
[](https://dsdmoj.atlassian.net/browse/CT-3816)
View first three tabs H1 titles

CT-3816 h2  titles to main pages

---

app/controllers/application_controller.rb
app/views/shared/_navigation.html.slim

Update page title suffix and make nav keep working.
n/a
[](https://dsdmoj.atlassian.net/browse/CT-3795)
n/a

CT-3795 Update title suffix and realign nav highlight

---

app/assets/stylesheets/pq.scss
app/views/dashboard/_question_data.html.slim

Reposition heading and checkbox for PQ in list - mainly for accessibility to have a proper clickable label and checkbox and separation of link, but also for layout.
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-3817
n/a
See PQ list on New/In Progress/Backlog and filter pages

CT-3817 reposition PQ heading / label in list

---

app/assets/stylesheets/pq.scss

improve contrast of cross for action officer
before: 
after:
[](https://dsdmoj.atlassian.net/browse/CT-3833)
On dashboard, add action officer to a PQ

CT-3833 improve contrast of cross for action officer

---

app/assets/stylesheets/pq.scss

Darken contrast of dates from/to to meet AA
before
after
https://dsdmoj.atlassian.net/browse/CT-3834
Go to backlog page and check date filters

CT-3834 darken from/to colours

---

config/initializers/action_dispatch_patch.rb

Using patch as there is a dependency clash with some of the apps other
dependencies that will be harder to upgrade.
Details: https://github.com/advisories/GHSA-2rqw-v265-jf8c
App should start as normal and be accessible.

Uses initializer to patch actionpack / actiondispatch

---

.circleci/config.yml
config/pipeline/aws_ecr_scan_results.py

Make ECR scan script non-blocking

Make ECR scan script non-blocking

---

app/assets/stylesheets/pq.scss

Space out links on Settings page for easier tapping/clicking/reading
before
after
https://dsdmoj.atlassian.net/browse/CT-3870
Click on setttings

CT-3870 Space out links on settings page

---

app/views/shared/_navigation.html.slim

Make search button accessible by adding text
before
after
https://dsdmoj.atlassian.net/browse/CT-3822
n/a
Disable styles then check search box near top

CT-3822 Fix non-styled view for Search box to show Go button

---

app/assets/stylesheets/pq.scss
app/views/dashboard/_dashboard_filter.html.slim
app/views/reports/filter_all.html.slim

Improve filters form, where legends and fieldsets are added as appropriate in a consistent manner. Note: Keywords doesn't have multiple fields so no need for fieldset/legend.
before:
after:
https://dsdmoj.atlassian.net/browse/CT-4001
Go to any main page esp Backlog, and check filters without styles.

CT-3821 Fix form mark-up for filters

---

deploy.sh
k8s-deploy/development/ingress-live.yaml

This PR is to migrate PG dev from live-1 to live
https://dsdmoj.atlassian.net/jira/software/c/projects/CT/boards/25?modal=detail&selectedIssue=CT-4061

EKS migration for PG dev from live-1 to live

---

deploy.sh
k8s-deploy/staging/ingress-live.yaml

This PR is for migrating PQ staging into live
https://dsdmoj.atlassian.net/jira/software/c/projects/CT/boards/25?modal=detail&selectedIssue=CT-4061

CT-4061 EKS migration for staging

---

deploy.sh
k8s-deploy/production/ingress-live.yaml

migration for production env 
https://dsdmoj.atlassian.net/jira/software/c/projects/CT/boards/25?modal=detail&selectedIssue=CT-4061

CT-4061 EKS migration for production

---

k8s-deploy/production/ingress-live.yaml
k8s-deploy/production/ingress.yaml

This PR is to update ingress for production traffic switch
https://dsdmoj.atlassian.net/jira/software/c/projects/CT/boards/25?modal=detail&selectedIssue=CT-4061

CT-4061 Updated the ingress to reflect the traffic switch on live

---

app/assets/javascripts/pq.js
app/views/dashboard/_question_data_uncommissioned.html.slim
app/views/shared/_minister_selection.html.slim

Clean up New page form mark-up and fix labels, remove uneccessary JS, remove fieldsets with no legend
Non styled
Before: 
After:
https://dsdmoj.atlassian.net/browse/CT-3825
n/a
go to new page and click on labels

CT-3825 remove malfunctioning JS and fix labels

---

app/assets/stylesheets/moj/_forms.scss
app/assets/stylesheets/vendor/bootstrap.scss
app/views/shared/_navigation.html.slim

Add label to search field
before
after
https://dsdmoj.atlassian.net/browse/CT-3828
View any page and click on "Search by UIN" - should land in textbox

CT-3828 Add label to search form and remove extra li

---

app/assets/javascripts/load_time.js

Add response time metric to PQ - as per other products. Only difference is PQ doesn't use modules.
https://dsdmoj.atlassian.net/browse/CT-4021
Check GA realtime

CT-4021 Response time metric script

---

app/assets/javascripts/pq.js

When you click cancel, focus on the button that you just came from
This area: 
https://dsdmoj.atlassian.net/browse/CT-3829

CT-3829 Focus on input box if cancel is pressed in quick actions

---

app/assets/stylesheets/pq.scss
app/views/admin/index.html.slim

Add HTML5 Nav element around settings nav
https://dsdmoj.atlassian.net/browse/CT-3871

CT-3871 Add nav element around settings nav

---

app/controllers/pqs_controller.rb

Update whitelist to allowlist

---

k8s-deploy/development/ingress-live.yaml
k8s-deploy/production/ingress-live.yaml
k8s-deploy/staging/ingress-live.yaml

Adds default modsecurity to application ingress

Add default modsecurity

---

k8s-deploy/development/ingress-live.yaml
k8s-deploy/production/ingress-live.yaml
k8s-deploy/staging/ingress-live.yaml

Reverts ministryofjustice/parliamentary-questions#831

Revert "Add default modsecurity"

---

app/views/action_officers/show.html.slim
app/views/actionlist_members/show.html.slim
app/views/deputy_directors/show.html.slim
app/views/directorates/show.html.slim
app/views/divisions/show.html.slim
app/views/early_bird_members/show.html.slim
app/views/ogds/show.html.slim
app/views/press_desks/show.html.slim
app/views/press_officers/show.html.slim
app/views/users/show.html.slim
app/views/watchlist_members/show.html.slim

CT-3873 Add pipe and space between bottom links
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-3873

CT-3873 Add pipe and space between bottom links

---

lib/export/base.rb

Adds the group email for an action officer to the CSV export 
Settings > export to CSV > should see new column now "Group email" with the group email added for each Action Officer for the PQ in question.

Add group email to CSV export

---

app/assets/stylesheets/pq.scss

CT-3876 space out links in watchlist header
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3876

CT-3876 space out links in watchlist header

---

app/assets/stylesheets/moj/_forms.scss
app/assets/stylesheets/pq.scss
app/views/export/index.html.slim

Use legend in fieldset for accessibility
No significant visual changes
https://dsdmoj.atlassian.net/browse/CT-3879

CT-3879 Use legend instead of H2

---

app/models/early_bird_organiser.rb
config/locales/en.yml

CT-3882 Make validation match labels for early bird organiser
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-3882
Settings > Early bird organiser - try submitting blank form

CT-3882 Make validation match labels for early bird organiser

---

app/views/shared/_minister_selection.html.slim

Fix form label for Minister
no change
https://dsdmoj.atlassian.net/browse/CT-3839
Click on PQ -> Commission tab -> Then click on Action officer label - should land in dropdown

CT-3839 Fix labels

---

app/views/action_officers/index.html.slim
app/views/reports/report.html.slim

Add scope to table headers because of having 2-dimensional table
n/a
https://dsdmoj.atlassian.net/browse/CT-3849
n/A
View any report and inspect on row/col headers to check scope

CT-3849 scope attributes for 2d table

---

app/controllers/early_bird_organiser_controller.rb
app/views/admin/index.html.slim
app/views/early_bird_organiser/new.html.slim

Change early bird organiser title to "Suspend early bird Email" and add a tab title.
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3880
Go to settings > Suspend early bird email

CT-3880 Update titles for early bird suspension

---

app/assets/stylesheets/moj/_forms.scss

Make all labels resize, some were not working. Ticket was in QA, small fix remaining. Original PR: https://github.com/ministryofjustice/parliamentary-questions/pull/873
https://dsdmoj.atlassian.net/browse/CDPT-161

CDPT-161 Globally label font size resizable

---

k8s-deploy/development/ingress-live.yaml
k8s-deploy/production/ingress-live.yaml
k8s-deploy/staging/ingress-live.yaml

ingress update

---

app/assets/javascripts/load_time.js
app/views/layouts/application.html.slim
lib/settings.rb
public/400.html
public/401.html
public/403.html
public/404.html
public/405.html
public/406.html
public/408.html
public/411.html
public/413.html
public/415.html
public/416.html
public/422.html
public/423.html
public/424.html
public/500.html
public/501.html
public/504.html
public/nginx/500.html
public/nginx/505.html

Setup GA4 and keep GA3 running. Use tagman to control tags and remove old code.
https://dsdmoj.atlassian.net/browse/CDPT-216
Check that GA3 and GA4 are tracking page views and Page Load Time event

CDPT-216 Setup GA4 and Tagman

---

app/controllers/action_officers_controller.rb
app/helpers/application_helper.rb
app/models/action_officer.rb
app/views/action_officers/index.html.slim
features/action_officer_spec.rb
spec/models/action_officer_spec.rb

- Add links which toggle View Action Officer and View Inactive Action Officer views.  
- Feature tests added to test the links toggle and correct action officers listed for the view selected.

Cdpt 364 view inactive ao list

---

.circleci/config.yml
k8s-deploy/development/migration_job.yaml

remove useless secret from deployment file

CDPT-471 Remove useless secret from job deployment

---

.github/CODEOWNERS
.gitignore
app/helpers/application_helper.rb
app/views/early_bird_dashboard/index.html.slim
config/application.rb
features/early_bird_spec.rb
k8s-deploy/development/config_map.yaml

- Mail feature to email parliamentary questions team from early bird list

CDPT-440 mailto link

---

app/views/pages/accessibility.html.slim

CDPT-533 Fix typo in word remediation on Accessibility statement
https://dsdmoj.atlassian.net/browse/CDPT-533

CDPT-533 Fix typo in word remediation on Accessibility statement

---

k8s-deploy/development/config_map.yaml

update flag in main

---

k8s-deploy/production/config_map.yaml

PQ Tracker changes in Development and Staging environment are hidden using a feature flag.  Set the flag ready for deployment to production.
https://dsdmoj.atlassian.net/browse/CDPT-748?atlOrigin=eyJpIjoiNzJjMWE2N2NiMjgzNDdlZWJiYWQzMTY1YmY0ZjFlMGYiLCJwIjoiaiJ9
(https://dsdmoj.atlassian.net/browse/CDPT-682?atlOrigin=eyJpIjoiYzA3ZWE1NTVjMDY3NGQwZGJlNzA1YmFhM2M5NTgyMmUiLCJwIjoiaiJ9)
feature flag added to production environment in readiness for deployment to production.
FEATURE_PROPOSE_AO_ENABLED: "1"

CDPT-748 PQ: Add feature flag to production environment and set

---

.circleci/config.yml

Cdpt 763 pq migrate to short lived credentials

---

.circleci/config.yml
Gemfile
Gemfile.lock
app/controllers/ping_controller.rb

Make build details available on /ping page.

CDPT-814 Add env vars to show build info

---

spec/lib/smoke_test_runner_spec.rb

Fix smoke test runner tests

---

app/assets/javascripts/pq.js
app/assets/stylesheets/pq.scss
app/views/dashboard/_dashboard_filter.html.slim

Style changes in response to the PQ Tracker accessibility audit Dec 2022. Sections 1.13, 1.14 and 10.2
Followed design guide: https://design-system.service.gov.uk/get-started/focus-states/
Used `aria-labelledby` rather than `aria-describedby` as it doesn't work within MacOs Voiceover screenreader https://discussions.apple.com/thread/254083513. Used `aria-label` for the keywords filter group as there is no parent id for the keywords section.
For the `commission` button, using `aria-disabled` rather than `disabled` as recommended, allows the user to tab over and click on the 'commission' button, this still prevents form submission if the form isn't fully completed.
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-520

Update disabled button focus, visible focus indicator and form groupings

---

app/models/pq.rb

Restore the uniqueness of the PQ.UIN which was commented out.
[](https://dsdmoj.atlassian.net/browse/CDPT-1100?atlOrigin=eyJpIjoiNzAyNDQ5MGI0YWI0NDEyMTg3NThmNGY4MGM3YTQ3YzkiLCJwIjoiaiJ9)

CDPT:1100 - PQ: reintroduce uin unique

---

lib/settings.rb

Removes need to set ENV vars before running a server locally.

Allow local server without env vars

---

app/assets/stylesheets/moj/_navigation.scss

Makes the search bar height consistent with the search button, and makes the highlight on focus fully visible.
Before:
After:

Fix search bar height

---

app/models/pq.rb
db/migrate/20231107135812_add_index_to_pqs_uin.rb
db/schema.rb

Create a unique index for pqs on uin
https://dsdmoj.atlassian.net/browse/CDPT-1100?atlOrigin=eyJpIjoiM2YxNTM4Mzk2ODY5NDMyY2I1YTQwZDJhNmZlZDNjOWUiLCJwIjoiaiJ9
Need to run migration on staging and production environments

CDPT:1129 PQ: Create a PQS Unique Index on UIN

---

.circleci/config.yml

CDPT-1147: Use new image

---

app/assets/stylesheets/pq.scss
app/helpers/application_helper.rb
app/views/early_bird_dashboard/index.html.slim
app/views/proposals/new.html.slim
app/views/shared/_action_officer_selection.html.slim
config/application.rb
features/early_bird_spec.rb
k8s-deploy/development/config_map.yaml
k8s-deploy/production/config_map.yaml
k8s-deploy/staging/config_map.yaml

- Removes feature flag for the propose feature
- Remove ability to propose when question is already commissioned

CDPT-1231 Remove propose deputy director option when already commissioned

---

.circleci/config.yml

- Replaces deprecated image
- Fixes build tag for when branch name has slashes

CDPT-1423 Replace image

---

app/views/assignment/confirmation.html.slim
app/views/dashboard/_question_data.html.slim
app/views/dashboard/_question_data_uncommissioned.html.slim
app/views/dashboard/_quick_action_export.html.slim
app/views/export/index.html.slim
app/views/export/index_for_pod.html.slim
app/views/pqs/_pq_data.html.slim
app/views/watchlist_dashboard/index.html.slim
features/mi_statistics_spec.rb
lib/presenters/email.rb
lib/presenters/statistics.rb

Use to_formatted_s(:format) instead of deprecated to_s(:format)

---

.github/workflows/deploy.yml

Deployment rollout was failing due to unknown container name - https://github.com/ministryofjustice/parliamentary-questions/actions/runs/9582662994/job/26422477554

Fix container names

---

k8s-deploy/development/deployment.yaml
k8s-deploy/production/deployment.yaml
k8s-deploy/staging/deployment.yaml

Increase timeout for liveness and readiness probes to 15 seconds.

Increase timeout to 15 seconds

---

.github/workflows/deploy.yml

Update image for cronjob. This in turn will start the job at the required time.

Update cronjob image

---

db/migrate/20240626111426_add_archived_flag.rb
db/schema.rb

Adds `archived` boolean to PQs, and sets all questions from old sessions as archived.

Set old PQs as archived

---

.github/workflows/test.yml

https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-1818

Postgres 16 upgrade

---

app/controllers/early_bird_dashboard_controller.rb
app/models/pq_scopes.rb
spec/controllers/early_bird_dashboard_controller_spec.rb

This reverts commit daa5726d2afc0dd228e9b38b87d3631f9639eb64. (https://github.com/ministryofjustice/parliamentary-questions/pull/1066)
The previous change did not account for new questions added at the weekend.

CDPT-1993 Revert "CDPT-1866 Show all today's questions on earlybird (#1066)"

---

config/database.yml
lib/health_check/database.rb
spec/health_check/database_spec.rb

Non-standard config could cause issues when setting up the project for the first time.

Use more standard config for database.yml

---

app/controllers/early_bird_members_controller.rb
app/helpers/application_helper.rb
app/models/action_officer.rb
app/models/early_bird_member.rb
app/views/early_bird_members/index.html.slim
spec/controllers/action_officers_controller_spec.rb
spec/factories/early_bird_members.rb
spec/models/action_officer_spec.rb
spec/models/early_bird_member_spec.rb

Allow toggling between active and inactive earlybird members.

CDPT-2256 List inactive earlybird members

---

.github/workflows/deploy.yml

These values are different for each namespace.

Add env vars per environment

---

.github/workflows/test.yml
spec/feature_helper.rb
spec/features/action_officer_spec.rb
spec/features/archive_session_spec.rb
spec/features/backlog_filter_spec.rb
spec/features/commission_question_spec.rb
spec/features/dashboard_new_filter_spec.rb
spec/features/dashboard_pq_select_spec.rb
spec/features/dashboard_spec.rb
spec/features/early_bird_filters_spec.rb
spec/features/early_bird_spec.rb
spec/features/in_progress_filters_spec.rb
spec/features/post_commissioning_spec.rb
spec/features/qa_draft_reminder_spec.rb
spec/features/qa_pq_edit_dates_spec.rb
spec/features/reassign_question_spec.rb
spec/features/rejecting_aos_spec.rb
spec/features/rejecting_questions_spec.rb
spec/features/transfer_in_pq_spec.rb
spec/features/transfer_out_pq_spec.rb

Temporarily suspending feature tests due to chromedriver breaking changes. For this test branch only!

Temporarrily suspending feature tests

---

app/assets/stylesheets/moj/_pq.scss
app/views/dashboard/index.html.slim
app/views/early_bird_dashboard/index.html.slim

Fix focus order sequence in pages with filters (Accessibility review section 1.12)
Current layout
Revised layout
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?selectedIssue=CDPT-523

CDPT-523 Fix focus order sequence in pages with filters

---

app/views/layouts/govuk_template.html.erb

Reverting the header style change.
Before:
After:

CDPT-2837 Revert header style change.
