app/models/pq.rb
spec/models/pq_spec.rb

Removed erroneous check excluding the ability to assign the Question's assignment to the current Action Officer

Reassign to currently accepting Action Officer.

---

app/controllers/application_controller.rb

Hot-fix to avoid a production issue whereby URLs displayed in email notifications appear with port 9180

[Hotfix] Avoid setting a port in action mailer options

---

Gemfile
Gemfile.lock
app/mailers/pq_mailer.rb
app/workers/import_worker.rb
lib/pqa/import.rb
spec/mailers/pq_accepted_mailer_spec.rb

- Delete hardcoded minister contact list and use the one built-into the app.
- minor fixes

Use minister contacts in mailers

---

app/assets/javascripts/trim_link.js
app/controllers/trim_links_controller.rb
app/models/trim_link.rb
features/trim_link_spec.rb
lib/trim/validator.rb
spec/fixtures/invalid_trimlink.tr5
spec/models/trim_link_spec.rb

- check trim file is textual and has the expected header line before uploading it.
- ensure trim link controller returns the correct status code (400) when trim file is not valid.
- tweak JS

Security fix: check trim link content before uploading

---

app/views/pqs/_trim_link.html.slim
app/views/shared/_trim_link.html.slim

This is really a ugly patch. Perhaps we should do a better handling of soft-deletion at the model level

Do not display soft-deleted trim links

---

README.md
config/unicorn.rb
docker/rails/unicorn.service

unicorn.service was not explicitly setting the config file, hence spawning only 1 worker process (we default to 4 now)

HOTFIX: Update docker config to use at least 4 unicorn workers

---

app/controllers/pqs_controller.rb
app/views/dashboard/_question_data_uncommissioned.html.slim
features/rejecting_aos_spec.rb
spec/support/features/pq_helpers.rb

Make sure that selected minister and policy minister values persist even after the PQ gets manually re-commissioned

Bugfix: Sticky minister fields

---

README.md
app/controllers/dashboard_controller.rb
app/models/pq.rb
app/models/pq_counts.rb
app/models/pq_scopes.rb
db/migrate/20150331154333_remove_sorting_related_columns.rb
db/schema.rb
features/import_spec.rb
lib/pqa/import.rb
spec/models/pq_spec.rb
spec/support/db_helpers.rb

Fully decouple the dashboard sorting functionality from the import module. This implementation uses Postgres `DATE_PART` function to compute the `days_from_date_for_answer` at run-time. We also got rid of the `date_for_answer_has_passed` column. Expired PQs are still listed first for their timestamp delta value will be negative, and we are sorting in ascending order.

Simplify sorting

---

app/models/pq.rb

Unable to do migration 20150325143021_remove_progress.rb without the progress relation still being available in Pq, so this adds it back in temporarily

Fix to allow prod migrations to run

---

config/brakeman.ignore

Brakeman warns of a possible SQL injection in db_sanitizer.rb.  This is not a risk, as the variables that are being interpolated into the query string are not user-entered, therefore this has been added to the brakeman.ignore file

Add possible SQL injection warning to brakeman.ignore

---

.gitignore
app/controllers/application_controller.rb

- allow ApplicationController#page_not_found to be called without params (needed for default route)
- add postgres.log and brakeman-output.tabs to .gitignore

Deploy fix

---

spec/routes/routes_spec.rb

Implement basic tests for dashboard routes and non-existent route.  This test would have caught the issue we had with page_not_found expecting a parameter and not being given one.

test for routes

---

.gitignore
app/mailers/pq_mailer.rb
app/services/commissioning_service.rb
features/commision_question_spec.rb
spec/services/commissioning_service_spec.rb

New business process, removes the need for emailing Deputy Directors.

Remove deputy directors email

---

app/views/shared/_deadline_time.html.slim
features/post_commissioning_spec.rb

This fixes 2 errors when comparing times to check if a PQ is overdue:
1. the first time compared is the server time, stripped of its timezone offset. Eg, if it's 5am in the UK and the server is in Japan where it's 2pm, the server time will be returned as 2pm
2. the second time compared is the PQ's internal deadline. It is stored without time zone information and is converted as is to UK time (ie 2pm becomes 2pm GMT in the winter, and 2pm+1 in the summer)
The first error was probably introduced as a result of trying to fix the second one. Indeed, in winter and on a box that is set to UK timezone, both cancel each other out. But in the summer the result is one hour off, hence bug #96169910
This PR fixes both, although doesn't test for the 1st bug, as it doesn't seem to be possible to mock …

96169910 - correctly check if deadline passed

---

app/models/pq.rb
spec/models/pq_spec.rb

Fixes issue with Questions whose action officer has been inactivated - when the question was later saved, the progress flag inaccurately changed to 'Unallocated'
This was owing to a previous fix which did not take that scenario into account.

Dont ignore inactive aos

---

app/models/press_desk.rb
spec/models/press_desk_spec.rb

Press officers that are inactive won’t be added to the CC list anymore.

CC list error

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Sometimes we get this warning:
```
. (called from block in tsort_each at /usr/local/lib/ruby/2.3.0/tsort.rb:228)
DEPRECATION WARNING: You did not specify a `log_level` in `production.rb`. Currently, the default value for `log_level` is `:info` for the production environment and `:debug` in all other environments. In Rails 5 the default value will be unified to `:debug` across all environments. To preserve the current setting, add the following line to your `production.rb`:
config.log_level = :info
```
so now we specify an explicit log level for each environment.

Adds explicit logging and removes warning

---

docker-ng/rails/run-pq.sh
lib/tasks/user.rake

This change will detect the environment using HostEnv for the user creation 
rake task. The Dev env in AWS is running with RAILS_ENV=production so when  
seed/migration tasks are running currently no users are being created.
After merging this a user will be created during the "seed" rake task, in all envs except the real production. This means in "dev" an admin user will get created unless overridden by RAILS_USER.

Tweak environment detection in user creation task

---

docker-ng/rails/Dockerfile

Pass YES flag to apt-get install to prevent apt-transport-https
from blocking for interaction. It is currently upgrading libapt-pkg4.12
as a side effect which causes it to prompt for confirmation.

When installing apt-transport-https pass yes flag

---

app/views/shared/mailer/_email_signature.html.slim
app/views/shared/mailer/_email_signature_plain.text.slim

Because the phone number has changed

Amend phone number

---

lib/tasks/bugfix.rake

The API from Parliament does not treat each question's UIN as unique over time, instead the numbers reset at the beginning of a new Parliament. To avoid clash, though not elegantly, we prefix with a different character for each new Parliament. The application is due to be superceeded so this approach is effective in the short term.

Amend rake task for prefixing old questions

---

lib/tasks/early_bird.rake

So that the EarlyBird email is not sent during the summer recess 2017

Amend rake task for earlybird dates

---

.env.sample
config/README.md

After installing on a new machine we discovered an env variable that was needed to run the application locally was not specified in the README. This adds that it is needed to local development

Add missing env variable to setup instructions

---

lib/tasks/early_bird.rake

Sending blocked between 23/12/2019 and 06/01/2020.

Suppress the sending of early bird emails until Parliament restarts.

---

app/controllers/action_officers_controller.rb
app/controllers/actionlist_members_controller.rb
app/controllers/deputy_directors_controller.rb
app/controllers/directorates_controller.rb
app/controllers/divisions_controller.rb
app/controllers/early_bird_members_controller.rb
app/controllers/ogds_controller.rb
app/controllers/press_desks_controller.rb
app/controllers/watchlist_members_controller.rb
app/models/actionlist_member.rb
app/models/early_bird_member.rb
app/models/ogd.rb
app/models/press_desk.rb
app/models/watchlist_member.rb
app/views/action_officers/index.html.slim
app/views/actionlist_members/index.html.slim
app/views/deputy_directors/index.html.slim
app/views/directorates/index.html.slim
app/views/divisions/index.html.slim
app/views/early_bird_members/index.html.slim

Removed pagination from:
- Action Officers
- Deputy Directors
- Directorates
- Divisions
Removed inactive entries 48 hours after deactivation from: 
- Action list
- Early bird list
- Other Government Departments
- Press desks
- Watch list

Remove pagination and inactive accounts from admin pages.

---

.circleci/config.yml
config/database.yml
spec/health_check/database_spec.rb

From parliamentary-questions_test to parliamentary_questions_test as hyphens in the DB name break the our build pipeline.

Rename references to Dev environment DB

---

config/environments/development.rb
config/initializers/host_env.rb
k8s-deploy/development/deployment.yaml
k8s-deploy/development/migration_job.yaml
k8s-deploy/staging/trim_and_anonymise_database_cronjob.yaml

The URL generated for the emails included a port number from the
ActionBaseMailer settings in the config environments, this removes
where it is set.
Also fixes an issue where HostEnv.is_live? returns true for development
due to the regex ignoring the development prefix in the url. This caused
the migrations to error when deploying to development.

Fix url in email and sending host regex

---

k8s-deploy/staging/nightly_import_cronjob.yaml
k8s-deploy/staging/trim_and_anonymise_database_cronjob.yaml

Replace the leading '*' with '0' to make the jobs run once, on the hour.

Amend cron job scheduling.

---

app/mailers/notify_pq_mailer.rb
lib/presenters/email.rb

Replace depricated URI.escape method call with CGI.escape.
Remove trailing white space.

Fix Rubocop errors

---

app/mailers/notify_import_mailer.rb
spec/mailers/notify_import_mailer_spec.rb

- RAILS_ENV set correctly for each environment so SENDING_HOST comparision not needed
-  In local tests the RAILS_ENV set to 'test' therefore tests amended appropriately.

Output correct environment name in import email.

---

app/controllers/application_controller.rb
app/views/layouts/_banner.html.slim
app/views/layouts/application.html.slim
app/views/layouts/maintenance.html.slim
config/routes.rb

In order to prevent users from editing the database or uploading files - or changing any sort of state, in fact - during our migration to Cloud Platform, this PR introduces "Maintenance mode"
When a file is present in the rails root directory named maintenance.txt then the app redirects all HTTP requests to maintenance page.
When the file is not present, the app functions as normal.
Can't do a feature spec for this because it will break parallel tests - as soon as we write the file for the test in one thread to check the app behaviour, any other tests will break.
But as long as the test suite passes otherwise, I think we should be good.
This PR adds the banner when site is on and maintenance page when site is off

Added maintenance page and banner

---

app/services/early_bird_report_service.rb
spec/services/early_bird_report_service_spec.rb
spec/services/watchlist_report_service_spec.rb
spec/support/features/pq_helpers.rb

Use DateTime.now.utc to standardise test time as daylight saving transition causing tests to fail.

Fix failing early bird and watchlist tests.

---

.rubocop.yml
Gemfile
Gemfile.lock

Moderate security vulnerability found in rubocop-rails 2.4.2.

Bump rubocop-rails from 2.4.2 to 2.5.0

---

.rubocop.yml
Gemfile
Gemfile.lock
Guardfile
README.md

Setup and configured Guard gem with the following plugins:
- guard-brakeman
- guard-livereload
- guard-rspec
- guard-rubocop
Updated README file to include mention of Guard and removed the Travis build status.
Updated RuboCop exception file to allow Guard to use %r RegEx format in its config file.

Implementing guard gem

---

app/helpers/devise_helper.rb

CT-2889 Fix Rubocop 'content_tag' offence.
- Replace legacy syntax 'content_tag' command with 'tag'

CT-2889 Fix Rubocop 'content_tag' offence.

---

k8s-deploy/development/deployment.yaml
k8s-deploy/development/ingress.yaml
k8s-deploy/production/deployment.yaml
k8s-deploy/production/ingress.yaml
k8s-deploy/staging/deployment.yaml
k8s-deploy/staging/ingress.yaml

Prepare for Kubernetes upgrade to 1.16
https://dsdmoj.atlassian.net/browse/CT-2942 (task)
https://dsdmoj.atlassian.net/browse/CT-2890 (ticket)
Need to apply Ingress and Deployment files at the very least. Might be best to full deploy anyway.
First deploy dev / staging etc, and see if it works. Then prod. And then...
Check if the application still works on all namespaces after CP upgrade the week commencing API on 12th July.

CT-2942 Remove deprecated k8s apis june 2020

---

Gemfile.lock

Fix broken styling in Select2 style dropdown lists.  Select2 gem version above 4.0.5 cause this behaviour.

revert-select2-rails-to-v4.0.5

---

.circleci/config.yml

Remove docker layer caching to save 200 credits per run (may marginally slow down the build, but not a big deal)
BEFORE:
AFTER:
(didn't really slow down)
https://dsdmoj.atlassian.net/browse/CT-3135
use circle ci, and make sure it works
Nothing should change except build time for docker image, and not much.

CT-3135 Remove docker layer caching to save cost

---

k8s-deploy/production/cronjob-delete-old-ecr-images.yaml

Increase number of left over master images to 25 for safety against losing the one on production (if 10 master images are built, that are not on prod, then the prod one would be deleted).- so reduce risk - make it 25
https://dsdmoj.atlassian.net/browse/CT-3302
n/a
n/a - once on production, we should gradually see master images increase to 25. this can be tested by querying the images using this command: aws ecr list-images --region eu-west-2 --repository-name [repo name]  --query 'imageIds[*]' --output json

CT-3302 Up master images to keep to 25

---

lib/tasks/early_bird.rake

The early bird email is not to be sent out from 20.12.2020 to 04.01.2021.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3318
Nothing special needed for deployment
Check the date range set in line 5 of lib/tasks/early_bird.rake.  The early bird email is to be suppressed from Sunday the 20th December as questions tabled of Friday need to be sent out on Saturday 19th December.  The process will restart on the 5th January 2021.

CT-3318 Stop sending the early bird emails over christmas

---

app/views/shared/_minister_selection.html.slim

Add blank first line in the answering Minister dropdown when displayed on the Dashboard page only.
Currently, all 'in progress' questions can have the answering Minister changed via a dropdown list on the 'In progress' page 'PQ commission' tab.  This dropdown list has a blank first option which can be accidentally chosen.  This null value breaks subsequent attempts to render the 'In progress' page.
The blank dropdown option makes no sense in the context of a commissioned question.  Therefore it should be removed.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3112
1) Commision a question on the dashboard, setting yourself as the Action Officer.
2) Accept the PQ from the link found in the email the system sent you. 
OR
Manually …

CT-3112 Prevent answering Minister removal from commissioned PQs

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/moj/_alert-banner
app/views/layouts/_banner.html.slim
app/views/layouts/application.html.slim

Add a banner that can be re-used if needed for PQ Tracker RDS upgrade
Note: It seems we're not using en.yml for the text on PQ Tracker, so sticking with that now. But at some point I may tidy that up.
https://dsdmoj.atlassian.net/browse/CT-3419
n/a
Nice banner should show

CT-3419 Add reusable alert banner for RDS upgrade

---

lib/tasks/early_bird.rake

Stop sending early bird emails from 11th to 22nd Feb while Parliament is in recess.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3450

CT-3450 Suppress early bird email

---

app/controllers/ao_token_filter.rb
app/controllers/application_controller.rb
lib/pq_statistics/percent_on_time.rb

When running ‘rspec features’ tests the following warnings are output:
`DEPRECATION WARNING: render file: should be given the absolute path to a file (called from log_and_redirect at /Users/nickpreddy/Desktop/Repositories/parliamentary-questions/app/controllers/ao_token_filter.rb:31)`
`DEPRECATION WARNING: render file: should be given the absolute path to a file (called from block (2 levels) in show_error_page_and_increment_statsd at /Users/nickpreddy/Desktop/Repositories/parliamentary-questions/app/controllers/application_controller.rb:84)`
and
`DEPRECATION WARNING: NOT conditions will no longer behave as NOR in Rails 6.1. To continue using NOR conditions, NOT each condition individually (.where.not(:answer_submitted => ...).where.not(:date_for_answer => ...)). (called from pq_data at …

Ct 3495 fix deprecation warnings

---

lib/tasks/early_bird.rake

The House of Commons begins Easter recess on the 27th March until 13th April.  As no questions will be asked during this period there is no need to send out the daily early bird email.
Questions asked on the 25th will not appear until the morning of the 26th, thus early bird suppression starts from the morning of 27th.  Likewise, all questions asked on 13th will not appear until the morning of the 14th.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3527
Test the happy path, check all is as expected.

CT-3527 Suppress early bird over easter recess

---

Gemfile.lock

RE: https://github.com/rails/rails/issues/41750
The application will not build due to all versions of mimemagic gem below 0.3.6 being pulled by the maintainer.
PQs dependency is currently rails (6.0.3.4)/activestorage (6.0.3.4)/marcel (0.3.3)/ mimemagic (0.3.5)
The difference between mimemagic 0.3.5 & 0.3.6 is a change in from MIT to GPL v2.0 licenses.
Upgrading 0.3.6 fixes build problems.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&selectedIssue=CT-3562
Please test the happy path (Has been deployed to Dev and Staging).

CT-3562 Update mimemagic gem to v0.3.6

---

lib/tasks/early_bird.rake

Set early bird email to stop on 4th May 2021, resuming on the 12th May 2021.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3601
Deployed to both Dev and Staging environments for testing
Please test the 'happy' path for any obvious issues.

CT-3601 - Suppress the early bird email during prorogue period 

---

lib/tasks/bugfix.rake

Prefix 2019-21 Parliamentary session questions with a '£'
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3602
This updated rake task has been deployed and actioned on both Dev and Staging environments
Please check the 'happy path' for any obvious glitches.  A  questions in both environments will be prefixed with a '£' character only.

CT-3602 Prefix 2019-21 Parliamentary session questions with a '£'

---

app/mailers/notify_pq_mailer.rb
app/services/early_bird_report_service.rb

From time to time customers will receive an early bird email with a malformed URL:
https://100.101.185.223/early_bird/...
The hostname is being replaced with an IP number.  The correct URL format is:
https://trackparliamentaryquestions.service.gov.uk/early_bird/...
To fix this we explicitly add the environment hostname to the link definition.  As there is no queue when firing emails to a list of customers, a half second delay has been temporarily introduced after calling the delivery method.  
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3631
This branch has been deployed to both Dev and Staging environments
This branch has been tested once by firing the early bird from staging to fellow developers.
To do this you need to log …

CT-3631 Fix early bird email malformed link URL

---

lib/health_check/database.rb
spec/health_check/database_spec.rb

Replace ActiveRecord::Base.connected? 
This method no longer reliably returns "true" when asking if the db is visible. If there has been no query within a certain timeframe, the connection is released and this method returns false although
any query will reconnect
We can use the newer ActiveRecord::Base.connection.active? which doesn't have this behaviour and returns true if the db
can be accessed, not "is connected"
n/a
https://dsdmoj.atlassian.net/browse/CT-3650
n/a
n/a

CT-3650 Replace ActiveRecord::Base.connected?

---

app/controllers/health_check_controller.rb
config/initializers/sentry.rb
k8s-deploy/development/deployment.yaml
k8s-deploy/production/deployment.yaml
k8s-deploy/staging/deployment.yaml

We're seeing high levels of pod restarts on all namespaces but particularly on production. One reason is that the liveness probe uses the `/healthcheck` endpoint which has dependencies on multiple external services responding over http, and the default timeout for Kubernetes probes is just 1s - so it fails regularly although the remote services are there (false positive), and if there are three in succession the pod gets restarted for no valid reason.
This PR changes the liveness and readiness probe endpoints to `/ping.json` to bring it into line with other services and for practical reasons. One reason is that if the PQ API is absent for any reason, this is _not_ a good reason to take down the PQ service. We do want to get alerted to it, which will happen because the Pingdom check will …

CT-3650 investigate pod restarts and instability 

---

lib/tasks/early_bird.rake

Parliament will be in recess from the 28th May until the 7th June.  During this time no questions will be tabled.  As such there is no need to send out the early bird email.
This amendment prevents the early bird email from dispatched from Saturday 29th may (It will need to go out on the 28th May). Normal service will begin on the 7th June.
N/A
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&projectKey=CT&modal=detail&selectedIssue=CT-3659
N/A
Please test for regressions on the Staging environment.

CT-3659 Suppress early bird email from 29th May until 7th June

---

app/mailers/notify_pq_mailer.rb

This PR is to make sure the host in the email is the one we intent to,  in general,  the host shouldn't need to be specified,  but somehow in some cases, the rails somehow couldn't decide what the host is,  instead, it uses the ip address from the pod in the cluster,  I spent some time to think about it, not quite sure how happened, it may related to the frequent-restarts or something else down to the environment outside app itself. 
The way used for this PR make sure the host is the one we configured ( which mean it may differ from the one hosted), but I would think it shouldn't cause any downsides as long as we always set  the url correctly in each env
No  tests needed 
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&modal=detail&selectedIssue=CT-2886

CT-2886 using the host from env to fix the  ipaddress issue

---

app/controllers/users_controller.rb

The issue that brakeman was complaining about is that admin was being allowed in .permit in the users_controller.rb. See why this can be an issue here: https://brakemanscanner.org/docs/warning_types/mass_assignment/ 
I think this was a mistake in that these params are only used on to update a user and the form that controls this has no :admin value to return. A completely filled in form has the following keys returned:
"user"=>{ "name"=>"New OldName",
"email"=>"admin@something.com",
"roles"=>"PQUSER",
"deleted"=>"0"}
Similarly the models in the app have no 'admin' flag at all.
I think this was just an oversight or left over from an earlier iteration of the page.
I have removed the :admin key here, and this brakeman warning no longer occurs …

CT-3692 Remove :admin key in param to stop Brakeman warning

---

app/views/reports/filter_all.html.slim

Fix filter status label and change wording to make more sense
before:
after: 
https://dsdmoj.atlassian.net/browse/CT-3867
n/a
Go to reports > (any report) > click on the name or the numbers in the report > click on "Status" - should take you into the dropdown. Also dropdown wording should say "Select status"

CT-3867 Fix status filter label and wording

---

app/views/dashboard/_question_data_uncommissioned.html.slim

Move commission button to end of form so when you zoom in or mobile view it's no in the middle of the form.
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3830

CT-3830 Move commission button to bottom of form

---

app/assets/stylesheets/vendor/bootstrap.scss

Add background colour to active tab. Using Bootstrap file because it's already been changed a lot - so vendor rules don't really apply.
Before on hover
After on hover
https://dsdmoj.atlassian.net/browse/CT-3847
n/a
Go to PQ detail page and tab through the tabs. When you tab through the active one it should go grey.

CT-3847 Add bg colour to active tab

---

app/views/dashboard/_quick_action_edit_dates.html.slim

Fix label for internal deadline field
this one.
https://dsdmoj.atlassian.net/browse/CT-3827
n/a
Click on the Internal deadline label, should land in the box

CT-3827 Fix field label in quick actions

---

app/assets/stylesheets/pq.scss

Fix contrast for Status filter "selected" text
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3832
n/a
Click on "Status" on right side then choose any. Selected should be dark purple.

CT-3832 Fix contrast selected filter

---

app/assets/stylesheets/pq.scss

Fix contrast of label under `Edit PQ Dates`
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3834
Go to In Progress page then click on `PQ dates` in sidebar

CT-3834 Fix label contrast in sidebar

---

app/assets/stylesheets/pq.scss

Fix contrast of label under `Edit PQ Dates`
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3834
Go to In Progress page then click on `PQ dates` in sidebar

CT-4006 redo overwritten commit

---

app/views/reports/filter_all.html.slim

Title in tab - first part - needs to say PQ filter.
Note: Related PR with decision to continue to not use translations - https://github.com/ministryofjustice/parliamentary-questions/pull/766
old
new
https://dsdmoj.atlassian.net/browse/CT-3866
Go to reports > Minister report then click on the name of any minister. Then check title in tab.

CT-3866 Add tab title to filter page

---

app/views/devise/passwords/new.html.slim
app/views/devise/unlocks/new.html.slim

Fix unlock page styling by making HTML consistent and fix title class for forgot password
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3811
n/a
Click on "Didn't receive unlock instructions?" On sign in page.

CT-3811 Fix unlock page style and forgot password title

---

app/controllers/application_controller.rb
public/400.html
public/401.html
public/403.html
public/405.html
public/406.html
public/408.html
public/411.html
public/413.html
public/415.html
public/416.html
public/422.html
public/423.html
public/424.html
public/500.html
public/501.html
public/504.html

add unhandled error pages for app with GA tracking so we can capture stats about when they occur. These may not all be used now but as and when they're included in the app or NGINX then errors should become more specific and display cleanly with Gov UK style, simple pages with consistency - and not required to change with app
e.g. 
before:
after
https://dsdmoj.atlassian.net/browse/CT-4028
Go to invalid URL, or cause server error, or navigate manually e.g /401.html

CT-4028 Add unhandled error pages

---

app/assets/stylesheets/pq.scss
app/views/pqs/_com_data.html.slim

Make non-accepted action officers section more accessible as per ticket
Before:
after:
https://dsdmoj.atlassian.net/browse/CT-3837
n/a
See PQ details page and click on Commission tab where action officers haven't accepted

CT-3837 Reorganise Action officers not accepted as per ticket screenshot

---

app/views/reports/filter_all.html.slim

Change wording for filter buttons to reflect what happens
before:
after:
https://dsdmoj.atlassian.net/browse/CT-3865
Go to any report and click on a link in the report. See filter buttons.

CT-3865 Change wording for filter buttons

---

app/views/early_bird_organiser/_form.html.slim
app/views/early_bird_organiser/new.html.slim
app/views/export/index_for_pod.html.slim

Replace heading with legend for fieldsets - also replace h2 with label for early bird
Before:
After:
(other changes negligible visual change)
https://dsdmoj.atlassian.net/browse/CT-3879
View settings pages under Tasks - fieldsets should have legends

CT-3879 replace heading with legend and h2 with label

---

app/assets/stylesheets/pq.scss

Fix contrast ratios of flags for accessibility - adjust colours
Before:
After:
https://dsdmoj.atlassian.net/browse/CT-3835
View reports to see flags - Click on Google Wave to check contrast errors

CT-3835 make flags pass contrast ratios

---

app/views/early_bird_organiser/_form.html.slim

Fix form labels on Early bird organiser and make button text consistent with others.
No significant visual changes
https://dsdmoj.atlassian.net/browse/CT-3881
Go to Settings > Early bird organiser. Click on labels. Also button should say "Save"

CT-3881 Fix labels and button text consistency

---

app/views/reports/filter_all.html.slim

CT-3869 Move filters above content as per homepage
n / a
https://dsdmoj.atlassian.net/browse/CT-3869
Squash to mobile portrait view on Filters page after clicking anything on reports. Filters should show at the top of the screen instead of bottom.

CT-3869 Move filters above content as per homepage

---

app/assets/stylesheets/pq.scss

Add gap below button for filter on mobile portrait view
Before:
AFTER:
https://dsdmoj.atlassian.net/browse/CT-3869
Click on reports > any number/name > filters page then shrink to mobile

CT-3869 Add gap below button on mobile

---

app/views/dashboard/_question_data_commissioned.html.slim
app/views/shared/_ao_reminder_link.html.slim

Make action officers and reminders a bit clearer and links more accessible
before: 
after:
https://dsdmoj.atlassian.net/browse/CT-3824
View PQs on the list pages New, In Progress, Filters

CT-3824 reorganise action officer reminder text

---

app/controllers/transferred_controller.rb

Fix browser page title when form is submitted on transfer page
n/a
https://dsdmoj.atlassian.net/browse/CT-3878
n/a
Go to ...
https://development.trackparliamentaryquestions.service.gov.uk/transferred/new
and submit empty form. Page title shouldn't change.

CT-3878 Fix page title for transfer page

---

app/views/admin/index.html.slim
app/views/dashboard/_questions_list.html.slim
app/views/dashboard/index.html.slim
app/views/early_bird_members/index.html.slim
app/views/users/index.html.slim
app/views/watchlist_members/index.html.slim

Move status messages under H1 tag 
Example: 
before
after
https://dsdmoj.atlassian.net/browse/CT-3875
n/a
See status message after making any form updates, should be under the page title

CT-3875 put flash messages under title

---

app/views/action_officers/index.html.slim
app/views/actionlist_members/index.html.slim

Missed a couple of status message moves - added them here (under H1)
(see previous PR)
https://dsdmoj.atlassian.net/browse/CT-3875
n/a
Add action officer or action list member - status message confirm should be under h1

CT-3875 Move action officers status under heading

---

.gitignore
build.sh
k8s-deploy/development/deployment_sidekiq.yaml
k8s-deploy/production/deployment_sidekiq.yaml
k8s-deploy/staging/deployment_sidekiq.yaml

Adjust probes to allow some leeway for sidekiq to respond before restarting pod.
https://dsdmoj.atlassian.net/browse/CDPT-487

CDPT-487 Adjust probes to prevent restarts

---

k8s-deploy/staging/deployment.yaml

PQ Tracking - staging environment has 4 pods and other ruby apps staging environments have only 1.  After a review with Nick and Javid we decided to reduce to 1.

CDPT-389: Reduce staging environment pods from 4 to 1

---

k8s-deploy/staging/nightly_import_cronjob.yaml
k8s-deploy/staging/trim_db_cronjob.yaml

Currently the Staging environment database is closes down from 10PM until 6AM UTC (11PM and 7AM BST) to save resources.  Unfortunately the cron job that pulls in the daily questions via the Parliament API gets triggered at 4AM and 6AM UTC (5AM and 7AM BST).  This means the first pull attempt always  fails.  The second pull attempt often fails depending on if the database is available in time.
The solution is to just change the cron job trigger times to 8AM & 10AM UTC  (9AM & 11AM BST). 
N/A
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152/backlog?view=detail&selectedIssue=CDPT-866&issueLimit=100
N/A
**Definition of Done**
Anyone with access to the support mailbox will receive two emails titled “staging – API import succeeded“.  One at 9AM the other at 11AM (BST).

CDPT-866 Change question import cronjob timing on Staging.

---

lib/pq_state/progress_changer.rb

Applying the RuboCop auto-correct to PQ made changes to the progress_changer.rb code.  These changes have cause some state changes to be skipped e.g. "Draft Pending" => "POD Query" instead of "With POD".  This PR reverts the changes and disables the RuboCop Style/DoubleNegation check on the effected lines.
N/A
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?modal=detail&selectedIssue=CDPT-876
N/A
1. Commission a question where you are the Action Officer.
2. Accept the assignment via the Allocation email.  The PQ status should now read "Draft Pending"
3. Go to the "In progress" tab.
4. Click on the "PQ draft" tad (left hand side)
5. Under "Date PQ returned by action officer" enter a date and time.
6. Click on Save.
7. The PQ stage should now be changed to "With POD" …

CDPT-876 Fix incorrect PQ state change.

---

Gemfile
spec/spec_helper.rb

Sinatra was only in the test group in the Gemfile, and a recent change excluded test dependencies when building the production image. Moving it out of the test group means it will be in the build.

Move Sinatra out of test group

---

app/views/shared/_navigation.html.slim

Style changes in response to the PQ Tracker accessibility audit Dec 2022. Section 1.6
It was recommended to change the Report nav dropdown `<a>` tag to `<button>`. However, Bootstrap allows for a `role` attribute for accessibility reader assist which will read the `<a>` as a `<button>` https://getbootstrap.com/docs/5.3/components/buttons/#button-tags - see Button Tags section

Tell screen reader that HTML <a> tag acts as a <button>

---

app/views/dashboard/_question_data.html.slim
app/views/layouts/application.html.slim
app/views/reports/report.html.slim
app/views/shared/_navigation.html.slim

Style changes in response to the PQ Tracker accessibility audit Dec 2022. Section 1.8
Using a screen reader the following is read aloud:
- Question details link reads "visited, link, view and edit question <_questionuid>"_
- PQ feedback links reads "link, click to send feedback via email, main"
- Navigation links which reads "visited, link, click to view <_nav-option_>"
- Report screen which reads "link, click to view questions for <_minister_name_>"
- Report screen table cells which reads "link, click to view questions with a status of <_report_status_>"
- Accessibility link in footer which reads "link, click to visit accessibility statement"
- Parliamentary branch link (which opens default emailer) in footer which reads "link, click to email parliamentary branch"
- MOJ digital services …

Add label to link purpose for screen reader

---

k8s-deploy/development/deployment_sidekiq.yaml
k8s-deploy/production/deployment_sidekiq.yaml
k8s-deploy/staging/deployment_sidekiq.yaml

There was an issue on another application where calling sidekiqmon was not working without using `bundle exec` in some instances. Sidekiq is loaded from the Gemfile, so best practice is to use `bundle exec`.

Use bundle exec on readiness/liveness check

---

app/assets/stylesheets/pq.scss
app/views/dashboard/_questions_list.html.slim
app/views/shared/_navigation.html.slim

Style changes in response to the PQ Tracker accessibility audit Dec 2022. Sections 1.11, 1.4, 1.5.
1.4 - added `aria-live="polite"` to `#count` element as a means to inform the screen reader that the number of filtered results has changed. Otherwise too much content will be read out. Example, the screen reader will read out "0 parliamentary questions out of 1." when filter results are updated.
1.5 - Added contrast to focus indicator on `filter` inputs (E.g. datepicker and keywords). Other dropdown contrasts were added in PR https://github.com/ministryofjustice/parliamentary-questions/pull/955
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-519

Allow screen reader to announce dynamic changes when filtered

---

app/views/action_officers/index.html.slim
app/views/actionlist_members/index.html.slim
app/views/deputy_directors/index.html.slim
app/views/directorates/index.html.slim
app/views/divisions/index.html.slim
app/views/early_bird_members/index.html.slim
app/views/ministers/index.html.slim
app/views/ogds/index.html.slim
app/views/press_desks/index.html.slim
app/views/press_officers/index.html.slim
app/views/reports/report.html.slim
app/views/users/index.html.slim
app/views/watchlist_members/index.html.slim

As per the accessibility audit, the screen reader should say which table the user is navigating into.
Using a `<caption>` element was recommended, however this created visible text then requiring a visually hidden class to be added. Instead, using aria-label on the table html tag works well.
Currently, when tabbing into a table, the screen reader says "Entering into table ...".
After the `aria-label` has been added:
When tabbing into the table, the screen reader now says "Entering into `<TABLENAME>` table ..."
When tabbing out of the table, the screen reader now says "Leaving `<TABLENAME>` ..."
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-524 
Tested using Macos CrossOver and WAVE evaluation browser extension

Add table captions

---

app/views/transferred/_form.html.slim

As per the accessibility report, labels for the radio groupings are needed to ensure the screenreader states which question they relate to.
The report recommends using a `<legend>` element however this creates visible text. Then requiring a `visually-hidden` class which is not read by the screen reader. Instead, `aria-label` allows the screenreader to say what question the button is for. 
Currently the screen reader says e.g. "House of commons, radio button, selection 1 of 2,"
With the `aria-label` the screen reader says e.g. "House of commons, radio button, selection 1 of 2, selection for house type, group"
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-525
Testing using Macos voiceover

Add label for radio button groups

---

app/views/action_officers/_form.html.slim
app/views/actionlist_members/_form.html.slim
app/views/deputy_directors/_form.html.slim
app/views/devise/passwords/new.html.slim
app/views/devise/sessions/new.html.slim
app/views/devise/unlocks/new.html.slim
app/views/directorates/_form.html.slim
app/views/divisions/_form.html.slim
app/views/early_bird_members/_form.html.slim
app/views/early_bird_organiser/_form.html.slim
app/views/export/index.html.slim
app/views/export/index_for_pod.html.slim
app/views/ministers/_form.html.slim
app/views/ogds/_form.html.slim
app/views/press_desks/_form.html.slim
app/views/press_officers/_form.html.slim
app/views/transferred/_form.html.slim
app/views/users/invitations/new.html.slim
app/views/watchlist_members/_form.html.slim

As per the accessibility report (1.9), required input fields should be clearly labelled and read by the screen reader. 
The report recommends adding the `required` attribute to the `<input>` tag, however this overwrites the currently used error notifications with the standard HTML5 browser input error notifications. 
Therefore, added "(required)" to form-group label to inform that it's a mandatory input, without having to be informed by the error notification after submitting the form.
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-529
Tested using Macos VoiceOver

Clarify required fields

---

app/views/pqs/show.html.slim

As per the accessibility report 9.2, the tab panels within PQ details should be accurately described by the screenreader.
Currently, when tabbing over an element the screen reader says e.g. "link, Finance check"
After adding `role="tablist"` to the parent `ul` and `role="tab"` to each `li` element. The screen reader says e.g. "Finance check, selected, tab, 2 of 7". 
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-531
Tested with MacOs VoiceOver

Accurate tab labels

---

app/views/dashboard/_question_data.html.slim
app/views/dashboard/_questions_list.html.slim

As per the accessibility report, the screen reader doesn't describe the question status or internal deadline date e.g. "draft pending" and "12/02/2020 11:00"
Currently when tabbing into a question within the question list, the screen reader omits the question status and internal deadline date e.g. "… link, click to view and edit question < QUESTION NUMBER > …"
After adding an `aria-label` when tabbing into a question the screenreader dynamically says e.g. “… link, click to view and edit question 123, question status draft pending, internal deadline 12/02/2020 11:00 (or, 'internal deadline not set') …”
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-532
Tested using MacOs VoiceOver CMD + F5

Labels for status and warnings

---

lib/tasks/bugfix.rake

Parliament in now in recess and a new session will begin next week.  With each new session the question "Unique identifying number" (UIN) resets to 1, meaning there could be a clash between new and historical question numbers.  To avoid this, when a session closes and before another begins, the last sessions questions need to be prefixed with a unique character.  This sessions character is 'b'.  The prefix_uins script has to be updated with this character and run in Staging and Production environments
This script looks for and ignores all questions carrying previous prefix characters ('#', '$', '^', '~', '£', and 'a')and appends 'b' to the begining of all the rest of the questions. so for example:
£3456829
#2015019
$2015010
a2015011
2015012
would become:
£3456829
#2015019
$2015010 …

CDOT-1082 Prefix last sessions questions with a 'b'.

---

config/brakeman.ignore
config/initializers/cookies_serializer.rb

Change serializer method to `hybrid`. This will allow users to stay logged in and update their cookies in place to use json.
New users logging in will use json to serialize their cookies.
In the future we can move to using the default `json` serializer.

CDPT-901 Change cookie serializer

---

app/views/pqs/_answer.html.slim

As per the accessibility report 9.5. Redundant content repeated by screen readers (L)
Create I will write follow up link highlighted on PQ details page
9.5.1. WCAG 1.3.1 (A) - Desktop
On the PQ details page, the “Create ‘I will write’ follow up” link has been assigned a title attribute which essentially repeats the text on the a element.
Repetitive content makes for auditory clutter, which can impose a cognitive load on screen reader users. As the wording in the title attribute doesn’t match up with the text on the a element, it may cause a jarring experience for some screen reader users with some vision.
9.5.2. Code snippet
<a id="create_iww" class="button-secondary" title="Create an I will
write follow up" href="/i_will_write/create?id=25077">Create 'I will write' follow up</a>
9.5.3. …

CDPT-528: Remove title element and amend link text

---

app/services/commissioning_service.rb
spec/services/commissioning_service_spec.rb

CDPT-779: AO rejection history should always be shown.
https://dsdmoj.atlassian.net/browse/CDPT-779?atlOrigin=eyJpIjoiM2I3M2M3MTU0NjZiNDFkYTlmMmNhMThjOTVlOWI1NGUiLCJwIjoiaiJ9

CDPT:779 AO rejection history should always be shown.

---

k8s-deploy/production/early_bird_dispatch_cronjob.yaml
k8s-deploy/production/nightly_import_cronjob.yaml
k8s-deploy/staging/early_bird_dispatch_cronjob.yaml
k8s-deploy/staging/nightly_import_cronjob.yaml
k8s-deploy/staging/trim_db_cronjob.yaml

The Cloud Platform Kubernetes cluster is being updated and support is being dropped for the current CronJob API we use.

CDPT-1147:PQ Remove beta1 version from cron jobs

---

app/views/pqs/show.html.slim

Changed the fieldset role from 'region' to 'group' as 'region' is not allowed for aria-live type 'polite'.
N/A
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-526
N/A
Please test the help paths for this application.

CDPT-526 PQ 9.1 - Change fieldset to div in tabs for ARIA role

---

app/models/pq.rb
app/views/dashboard/_question_data_commissioned.html.slim
app/views/pqs/_com_data.html.slim
spec/models/pq_spec.rb

Adds a not_rejected method to the action officers association so that only non-rejected action officers are listed against a PQ.

CDPT-1232 Don't show rejected Action Officers

---

config/application.rb

Removing the default because it stops form submissions working.

Don't load 6.1 defaults

---

app/assets/javascripts/pq.js
app/views/dashboard/_dashboard_filter.html.slim
app/views/dashboard/_quick_action_edit_dates.html.slim
features/backlog_filter_spec.rb
features/in_progress_filters_spec.rb
features/post_commissioning_spec.rb
features/qa_pq_edit_dates_spec.rb
features/transfer_in_pq_spec.rb
features/transfer_out_pq_spec.rb

The internal deadline filter on the Backlog and In Progress pages is not working.
The reason is that internal_deadline is stored as datetime, whereas date_for_answer is stored as a date. The Javascript that does the filtering was always expecting a date. This has been modified to use the correct format based on the field being filtered on.
---
The date placeholder has also been updated to a more recent date

CDPT-1736 Fix internal deadline filter

---

k8s-deploy/staging/config_map.yaml

The PQ staging namespace db_name was previously set to parliamentary_questions_dev which didn't make sense for its staging namespace. This was updated (https://github.com/ministryofjustice/cloud-platform-environments/pull/24359/files) which then severed the DB connection. Therefore, was advised by CP to update the config_map to fix the issue.

Update db configmap to match namespace

---

.github/workflows/test.yml

Upload of test coverage files stopped working due to a security [change](https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/) in the github action.
Fixed by using [new option](https://github.com/actions/upload-artifact/issues/602).

Allow hidden files in CI upload

---

.github/workflows/test.yml
app/views/layouts/govuk_template.html.erb

favicon is causing a 401 error which forces the basic auth dialog box to be reshown.

Use correct path

---

app/assets/stylesheets/moj/_pq.scss
app/javascript/moj/pq.js
app/views/early_bird_dashboard/index.html.slim

Remove the hyperlinks enclosing each of the question UINs on the early bird page.
**Before:**
**After:**
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-2200
N/A
View the Early bird preview page under: Settings / Early bird list / Early bird preview.  Questions UINs should no longer have hyperlinks.

CDPT-2200 Remove early bird question UIN hyperlinks

---

.github/workflows/deploy.yml

PRs created by Dependabot don't have the correct permissions to authenticate to Cloud Platform

Don't build if dependabot

---

app/views/dashboard/_question_data_commissioned.html.slim
app/views/dashboard/_question_data_uncommissioned.html.slim
app/views/pqs/_answer.html.slim
app/views/pqs/_com_data.html.slim
app/views/pqs/_minister_check.html.slim
app/views/pqs/_pod_check.html.slim
app/views/pqs/_pq_draft.html.slim
app/views/shared/_rejected_reasons.html.slim
app/views/transferred/_form.html.slim
config/initializers/time_formats.rb
spec/features/qa_pq_edit_dates_spec.rb

Ensure all timestamps in forms are formatted as `dd/mm/yyyy hh:mm`

Format date consistently

---

app/assets/stylesheets/moj/_pq.scss
app/views/pqs/_answer.html.slim
app/views/pqs/_com_data.html.slim
app/views/pqs/_minister_check.html.slim
app/views/pqs/_pod_check.html.slim
app/views/pqs/_pq_data.html.slim
app/views/pqs/_pq_draft.html.slim
app/views/pqs/show.html.slim

The vertical tab style in the details page is replaced with the GDS Design System horizontal tab component. This fixes the tab order issue described in the accessibility review (Section 9.3).
Current:
Proposed:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?selectedIssue=CDPT-1032

CDPT-1032 Fix PQ Details page focus order.

---

Gemfile.lock

Temporarily revert rack gem version to v3.1.8
Just the usual deployment steps
All tests should run without error when deployed to each environment.

Revert rack to version 3.1.8
